--DROP TABLE IF EXISTS comment;
--DROP TABLE IF EXISTS post;
--DROP TABLE IF EXISTS board;

CREATE TABLE IF NOT EXISTS `board` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(128) NOT NULL,
    `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `post` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `board_id` BIGINT UNSIGNED NOT NULL,
    `no` INT UNSIGNED NOT NULL,
    `title` VARCHAR(128) NOT NULL,
    `content` TEXT NOT NULL,
    `views` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`board_id`) REFERENCES board(`id`) ON DELETE CASCADE,
    INDEX idx_post (`board_id`)
);

CREATE TABLE IF NOT EXISTS comment (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `post_id` BIGINT UNSIGNED NOT NULL,
    `group` INT UNSIGNED NOT NULL,
    `sequence` INT UNSIGNED NOT NULL,
    `level` INT UNSIGNED NOT NULL,
    `content` VARCHAR(128) NOT NULL,
    `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`post_id`) REFERENCES post(`id`) ON DELETE CASCADE,
    INDEX idx_comment (`post_id`, `group`, `sequence`)
);

-- INSERT INTO post (board_id, no, title, content) VALUES(1, (SELECT IFNULL(MAX(no)+1, 1) FROM post AS p WHERE board_id=1), 'mytitle', 'mycontent');
